version: '2.1'
services:
  postgres:
    image: postgres:9.5
    restart: always
    volumes:
      - ./start.sh:/docker-entrypoint-initdb.d/start.sh
      - ./initialization.sql:/initialization.sql
    networks:
      a-project_default:
        ipv4_address: 172.29.0.2
    environment:
      - POSTGRES_USER=yclu
      - POSTGRES_PASSWORD=yclu
      - POSTGRES_DB=yclu
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yclu"]
      interval: 30s
      timeout: 30s
      retries: 5
  server:
    build: .
    restart: always
    volumes:
      - ./server.py:/app/server.py
      - ./database.py:/app/database.py
      - ./models.py:/app/models.py
    environment:
      - PGPASSWORD=yclu
      - PGUSER=yclu
      - PGDATABASE=yclu
      - APIKEY=<Your GOOGLE MAPs API KEY>
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
networks:
    a-project_default:
        name: project_python_default
        ipam:
            driver: default
            config:
                - subnet: "172.29.0.0/16"
                  gateway: "172.29.0.1"
